### ISSUE TITLE
how to contribute

### ISSUE THREAD

**Issue by tpoisonooo** [MegEngine/MegCC#12]
请问这个 repo PR 的规矩和 mge 一样要先  squash 成一个 commit 么？

啊希望不要。

**Comment by chenqy4933** [comment]
不用squash，后续主要在github上开发，最近正在支持github上的CI

**Comment by tpoisonooo** [comment]
好耶！

**Comment by tpoisonooo** [comment]
https://github.com/MegEngine/MegCC/pull/13  我加了个 CI
