### ISSUE TITLE
如何支持新的算子？

### ISSUE THREAD

**Issue by tpoisonooo** [MegEngine/MegCC#26]
我看算子列表的 opr 个数并不多，如果碰到个不支持的 （例如 topk）应该怎么办？

**Comment by chenqy4933** [comment]
kernel 数量确实不多，但是topk还真有了，另外已经有了一个粗糙的加 kernel 的文档，https://github.com/MegEngine/MegCC/blob/main/doc/how-to-add-new-kernel.md ， 可能不太清晰，后续补充一下
