### ISSUE TITLE
tcc demo miss link，where is the jit demo?

### ISSUE THREAD

**Issue by jsonlee0x01** [MegEngine/MegCC#3]
In the readme: <https://github.com/MegEngine/MegCC/blob/main/third_party/tcc/readme.md>
The following link is unreachable
https://www.developing-stuff.com/how-to-compile-run-c-code-at-runtime-or-how-to-use-c-as-a-scripting-language/

**Comment by chenqy4933** [comment]
yes， the origin link：https://www.developing-stuff.com/how-to-compile-run-c-code-at-runtime-or-how-to-use-c-as-a-scripting-language/ is out of data. delete it now.

**Comment by jsonlee0x01** [comment]
so where is the tiny demo for the jit impl, can you show the demo code?

**Comment by chenqy4933** [comment]
this is the demo used in MegCC, https://github.com/MegEngine/MegCC/blob/main/compiler/lib/KernelGen/Jit/JitExe.cpp#L75, hope it will help you!!!

**Comment by jsonlee0x01** [comment]
腾讯公司友情提醒：机主暂时奔出服务区、、、呵呵

**Comment by chenqy4933** [comment]
啥情况，看很久没有反应，就关了
