### ISSUE TITLE
x86上mobilenetv3模型变慢

### ISSUE THREAD

**Issue by nicheng0019** [MegEngine/MegCC#33]
mobilenetv3 large模型，直接从onnx格式转成mge格式，使用megengine运行，在输入尺寸为320x320的情况下，大概需要36ms，
使用megcc的

`mgb-to-tinynn mobilenetv3.mge ./x86  --enable_nchw44 --mgb_fuse_kernel`

和

`./runtime/scripts/runtime_build.py --kernel_dir ./x86`

命令转成.tiny格式，用tinynn_test_lite测试耗时大概为86ms，请问这个可能是什么原因？多谢！

**Comment by chenqy4933** [comment]
megcc 主要优化对象还是 Arm CPU，x86没有太关注性能，你在arm上测试一下呢？

**Comment by nicheng0019** [comment]
好的，谢谢，我在arm上试一下
