### ISSUE TITLE
megcc和TVM的比较

### ISSUE THREAD

**Issue by leikang123** [MegEngine/MegCC#51]
这个框架和TVM框架相比起来，有哪些优劣之处？

**Comment by chenqy4933** [comment]
MegCC is a deep-learning model compiler with the following features:

* Extremely Lightweight Runtime: Only keep the required computation kernel in your binary. e.g., 81KB runtime for MobileNet v1
* High Performance: Every operation is carefully optimized by experts
* Portable: generate nothing but computation code, easy to compile and use on Linux, Android, TEE, BareMetal
* Low Memory Usage while Boot Instantly: Model optimization and memory planning are generated at compile time. Get State-of-the-art level memory usage and spend no extra CPU during inference

**Comment by leikang123** [comment]
大概了解了。
