### ISSUE TITLE
源码编译不过

### ISSUE THREAD

**Issue by xzngycw** [MegEngine/MegCC#6]
源码编译报错：
 compiler/tools/mgb-to-tinynn/mgb-to-tinynn.cpp:102:19: error: ‘kernel_exporter’ has not been declared
     export_cv_opr(kernel_exporter, dump_info->cv_impl);

我看了好像确实没有kernel_exporter的声明。
是我哪里设置错了吗？还是这个开源代码就没有被正常编译通过？

**Comment by chenqy4933** [comment]
大概步骤是：
* 跑一下third_party下面的 prepare,sh
* 在compiler文件夹下面建立一个build文件夹，然后 cmake .. && make -j$(nproc)
这样的步骤吗？

开源工程是编译过的，因为预编译的可执行文件就是用这个工程编译的.

**Comment by chenqy4933** [comment]
感谢指出来，已经在：b7f5cb81d46ff1b8722ca6d6cdace86b4ebf371f 这个commit中修复了。
不好意思，项目刚刚弄好，CI还不健全，多多包容

**Comment by xzngycw** [comment]
修复后可以了编过了🤗，感谢开源，非常棒👍🏻的工作
